import type { AudioDevice, Voice, VoiceChangerConfig } from "./types"

export const VOICES: Voice[] = [
  {
    id: "original",
    name: "Original",
    description: "Your dry microphone signal — no effect.",
    category: "Clean",
    source: "system",
    initials: "MIC",
    isFavorite: false,
    tone: 0.05,
  },
  {
    id: "deep-narrator",
    name: "Deep Narrator",
    description: "Cinematic low-end. Trailers and storytelling.",
    category: "Cinematic",
    source: "rvc",
    initials: "DN",
    speaker: "Speaker 0",
    version: "v2",
    sampleRate: 40000,
    sizeMb: 56,
    hasIndex: true,
    tone: 0.18,
  },
  {
    id: "haruka",
    name: "Haruka",
    description: "Bright Japanese vocalist preset, +6 semitones.",
    category: "J-Pop",
    source: "rvc",
    initials: "HK",
    speaker: "Speaker 0",
    version: "v2",
    sampleRate: 48000,
    sizeMb: 73,
    hasIndex: true,
    tone: 0.42,
  },
  {
    id: "trump",
    name: "Trump",
    description: "Classic political impression, dialed for clarity.",
    category: "Celebrity",
    source: "rvc",
    initials: "TR",
    speaker: "Speaker 0",
    version: "v2",
    sampleRate: 40000,
    sizeMb: 84,
    hasIndex: true,
    isFavorite: true,
    tone: 0.61,
  },
  {
    id: "anime-girl",
    name: "Anime Girl",
    description: "Soft, expressive, +8 semitones bias.",
    category: "Character",
    source: "rvc",
    initials: "AG",
    speaker: "Speaker 0",
    version: "v2",
    sampleRate: 48000,
    sizeMb: 64,
    hasIndex: true,
    tone: 0.74,
  },
  {
    id: "robot",
    name: "Robot",
    description: "DSP-only metallic ring modulator.",
    category: "FX",
    source: "system",
    initials: "RB",
    sizeMb: 0,
    hasIndex: false,
    tone: 0.86,
  },
  {
    id: "alien",
    name: "Alien",
    description: "Detuned formant + reverb tail.",
    category: "FX",
    source: "system",
    initials: "AL",
    tone: 0.95,
  },
  {
    id: "morgan",
    name: "Morgan",
    description: "Warm, slow, gravel — narrator energy.",
    category: "Celebrity",
    source: "rvc",
    initials: "MG",
    speaker: "Speaker 0",
    version: "v2",
    sampleRate: 40000,
    sizeMb: 78,
    hasIndex: true,
    isFavorite: true,
    tone: 0.32,
  },
]

export const INPUT_DEVICES: AudioDevice[] = [
  { index: 0, name: "MacBook Pro Microphone", channels: 1 },
  { index: 1, name: "Shure MV7", channels: 2 },
  { index: 2, name: "Elgato Wave:3", channels: 1 },
  { index: 3, name: "Virtual Cable Input", channels: 2 },
]

export const OUTPUT_DEVICES: AudioDevice[] = [
  { index: 4, name: "MacBook Pro Speakers", channels: 2 },
  { index: 5, name: "AirPods Pro", channels: 2 },
  { index: 6, name: "BlackHole 2ch", channels: 2 },
  { index: 7, name: "VB-Cable Output", channels: 2 },
]

export const MONITOR_DEVICES: AudioDevice[] = [
  { index: 4, name: "MacBook Pro Speakers", channels: 2 },
  { index: 5, name: "AirPods Pro", channels: 2 },
  { index: 8, name: "Studio Monitors (UAD)", channels: 2 },
]

export const DEFAULT_CONFIG: VoiceChangerConfig = {
  inputDeviceIndex: 1,
  outputDeviceIndex: 6,
  monitorDeviceIndex: 5,
  inputVolume: 100,
  outputVolume: 100,
  monitorMix: 35,
  hearMyself: false,
  voiceChangerEnabled: true,
  sampleRate: 48000,
  bufferSize: 512,
  chunkMs: 256,
  f0Method: "fcpe",
  mode: "ai",
  pitchSemitones: 0,
  indexRate: 0.75,
  protect: 0.33,
  reverb: 0.1,
  reverbDamping: 0.5,
  noiseGateDb: -40,
  compressorRatio: 4,
  selectedVoiceId: "original",
}
